# image: https://hub.docker.com/r/typesense/typesense/tags
# docs: https://typesense.org/docs/guide/install-typesense.html
# https://typesense.org/docs/guide/docsearch.html#add-docsearch-meta-tags-optional

version: "3.8"

services:
  typesense:
    image: typesense/typesense:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:8108"
    environment:
      - TYPESENSE_API_KEY=${APP_KEY}
      - TYPESENSE_DATA_DIR=${APP_DATA_PATH}
    volumes:
      - typesense:/data

  docsearch-scraper:
    image: typesense/docsearch-scraper:latest
    container_name: ${APP_NAME}-scraper
    environment:
      - CONFIG={"index_name":"4d","start_urls":["https://developer.4d.com/docs/"],"sitemap_urls":["https://developer.4d.com/docs/sitemap.xml"],"sitemap_alternate_links":true,"stop_urls":[],"selectors":{"lvl0":"header h1","lvl1":"article h2","lvl2":"article h3","lvl3":"article h4","lvl4":"article h5","lvl5":"article h6","text":"article p, article li"},"strip_chars":" .,;:#","custom_settings":{"separatorsToIndex":"_","attributesForFaceting":["language","version"]},"conversation_id":["800622923"],"nb_hits":130834}
    depends_on:
     - typesense
      
networks:
  default:
    name: ${APP_NAME}

volumes:
  typesense:
