# image: https://hub.docker.com/r/typesense/typesense/tags
# docs: https://typesense.org/docs/guide/install-typesense.html

version: "3.8"

services:
  typesense:
    image: typesense/typesense:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:8108"
    environment:
      - api-key=${APP_NAME}
      - data-dir=${APP_DATA_PATH}
      - enable-cors=${APP_ENABLE_CORS}
    volumes:
      - "typesense:/data"
    depends_on:
      - mysql

networks:
  default:
    name: ${APP_NAME}

volumes:
  typesense:
