# image: https://hub.docker.com/r/typesense/typesense/tags
# docs: https://typesense.org/docs/guide/install-typesense.html

version: "3.8"

services:
  typesense:
    image: typesense/typesense:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:8108"
    environment:
      - TYPESENSE_API_KEY=${APP_KEY}
      - TYPESENSE_DATA_DIR=${APP_DATA_PATH}
    volumes:
      - typesense:/data

  docsearch-scraper:
    image: docsearch-scraper:latest
    container_name: ${APP_NAME}-scraper
    environment:
      - CONFIG=${APP_CONFIG}
    depends_on:
     - typesense
      
networks:
  default:
    name: ${APP_NAME}

volumes:
  typesense:
